### ISSUE TITLE
'Number of points too low' error in simulation

### ISSUE THREAD

**Issue by jainRAV** [neobotix/neo_localization2#15] opened 2022-07-14 01:33 UTC
Hi, I am trying this localization package with simulation (Ignition Gazebo). 
Here is the laser echo I am using (Published at 40Hz) 

header:                                                                                                                              
  stamp:                                                                                                                             
    sec: 892                                                                                                                         
    nanosec: 450000000                                                                                                               
  frame_id: front_laser_link                                                                                                         
angle_min: -2.3561999797821045                                                                                                       
angle_max: 2.3561999797821045                                                                                                        
angle_increment: 0.004363333340734243                                                                                                
time_increment: 0.0                                                                                                                  
scan_time: 0.0                                                                                                                       
range_min: 0.05000000074505806                                                                                                       
range_max: 20.0
ranges:
- 5.947685718536377
- 5.925894260406494
- 5.926396369934082
- 5.9155354499816895
...

**But still the neo_localization_node shows too low points as below:**

[neo_localization_node-3] [WARN] [1657760599.799568218] [neo_localization2_node]: NeoLocalizationNode: Number of points too low: 0
[neo_localization_node-3] [WARN] [1657760599.899551159] [neo_localization2_node]: NeoLocalizationNode: lookupTransform(m_base_frame, m_odom_frame) failed: Lookup would require extrapolation into the future.  Requested time 971.575000 but the latest data is at time 971.550000, when looking up transform from frame [base_footprint] to frame [odom]
[neo_localization_node-3] [WARN] [1657760599.899596416] [neo_localization2_node]: NeoLocalizationNode: Number of points too low: 0
[neo_localization_node-3] [WARN] [1657760600.499534485] [neo_localization2_node]: NeoLocalizationNode: lookupTransform(m_base_frame, m_odom_frame) failed: Lookup would require extrapolation into the future.  Requested time 971.925000 but the latest data is at time 971.900000, when looking up transform from frame [base_footprint] to frame [odom]

Here is the config:

neo_localization2_node:
  ros__parameters:
    base_frame: "base_footprint"
    odom_frame: "odom"
    # exponential low pass gain for localization update (0 to 1)
    #   (higher gain means odometry is less used / relied on)
    update_gain: 0.5
    # time based confidence gain when in 2D / 1D mode
    confidence_gain: 0.01
    # how many particles (samples) to spread (per update)
    sample_rate: 10
    # localization update rate [ms]
    loc_update_time: 100
    # map tile update rate [1/s]
    map_update_rate: 0.5
    # map tile size in pixels
    map_size: 1000
    # how often to downscale (half) the original map
    map_downscale: 0
    # how many 3x3 gaussian smoothing iterations are applied to the map
    num_smooth: 5
    # minimum score for valid localization (otherwise 0D mode)
    #    higher values make it go into 0D mode earlier
    min_score: 0.2
    # odometry error in x and y [m/m] [1]
    #    how fast to increase particle spread when in 1D / 0D mode
    odometry_std_xy: 0.01
    # odometry error in yaw angle [rad/rad] [1]
    #  how fast to increase particle spread when in 0D mode
    odometry_std_yaw: 0.01
    # minimum particle spread in x and y [m]
    min_sample_std_xy: 0.025
    # minimum particle spread in yaw angle [rad]
    min_sample_std_yaw: 0.025
    # initial/maximum particle spread in x and y [m]
    max_sample_std_xy: 0.5
    # initial/maximum particle spread in yaw angle [rad]
    max_sample_std_yaw: 0.5
    # threshold for 1D / 2D decision making (minimum average second order gradient)
    # if worst gradient direction is below this value we go into 1D mode
    # if both gradient directions are below we may go into 0D mode, depending on disable_threshold
    # higher values will make it go into 1D / 0D mode earlier
    constrain_threshold: 0.1
    # threshold for 1D / 2D decision making (with or without orientation)
    #   higher values will make it go into 1D mode earlier
    constrain_threshold_yaw: 0.2
    # minimum number of points per update
    min_points: 20
    # solver update gain, lower gain = more stability / slower convergence
    solver_gain: 0.1
    # solver update damping, higher damping = more stability / slower convergence
    solver_damping: 1000.0
    # number of gauss-newton iterations per sample per scan
    solver_iterations: 20
    # maximum wait for getting transforms [s]
    transform_timeout: 0.2
    # if to broadcast map frame
    broadcast_tf: true
    # Scan topic
    scan_topic: "scan/front"
    # Initial Pose topic
    initialpose: initialpose
    # Map Tile topic
    map_tile: map_tile
    # Map Pose topic
    map_pose: map_pose
    # particle_cloud topic
    particle_cloud: particlecloud
    # amcl_pose topic
    amcl_pose: amcl_pose

Do you know any reason why would this be happening?
Thanks

**Comment by automech-rb** [comment] 2022-07-14 10:46
Hi,
They seem to be very frequent (every 0.1 to 0.2 sec).
But the localization (map to odom transform) seems to work.

**Comment by automech-rb** [comment] 2022-07-14 11:16
This seems to be error on my side as this works perfectly on real Lidar.
Thanks.

Closing the issue for now.

**Comment by padhupradheep** [comment] 2022-07-14 11:42
No problem. Feel free to report if you find something else.

**Comment by fmros** [comment] 2022-09-14 12:53
Hy there, i have a similar issue with very frequent output of the following warnings in a simulation setup:
```
[neo_localization2_node]: NeoLocalizationNode: Number of points too low: 0
[neo_localization2_node]: NeoLocalizationNode: lookupTransform(m_base_frame, m_odom_frame) failed: Lookup would require extrapolation into the future.  Requested time 303.424000 but the latest data is at time 303.415000, when looking up transform from frame [base_link] to frame [odom]
```
It seems also from the RViz visualization that the localization ''jumps' a bit.
I traced it down to [this](https://github.com/neobotix/neo_localization2/blob/63728e413e063a46323fb6414b976ca3b51c9e2e/src/neo_localization_node.cpp#L235) line and when using the tf2::TimePointZero or a timeout, I was able to supress these warnings and obtained a more robust localization.
Why are you not requesting the latest available transform by the use of the  tf2::TimePointZero but using the scan timestamp?

**Comment by automech-rb** [comment] 2022-09-14 14:29
Hello @fmros 
I also faced similar problem before and I postdated odom tf by few microseconds (~equal to update interval of odom) to make the `lookupTransform` work.

I think using scan timestamp is correct implementation, as we would like to use odom data at the time scan was taken (also done in amcl package). But I am not sure postdating odom is a good solution. @padhupradheep do you have any suggestions?

**Comment by padhupradheep** [comment] 2022-09-14 17:10
> I think using scan timestamp is correct implementation, as we would like to use odom data at the time scan was taken (also done in amcl package).

@fmros, as @automech-rb told, this is the exact reason, else there will be again a tf warning of looking data into the past. This is because laser scanners usually publishes data at slower rates. For example, Sick S300 publishes data at a rate of close to around 12 Hz. In order to avoid race conditions, we tend to use the timestamps from the laser scanner data. 

> But I am not sure postdating odom is a good solution.

This maybe also caused because of the scanner delays, if you had faced it on a real laser scanner, which unfortunately is an inherent characteristic which we need to compensate.  Compensating by postdating odom would be one of the methods. 

> I traced it down to [this](https://github.com/neobotix/neo_localization2/blob/63728e413e063a46323fb6414b976ca3b51c9e2e/src/neo_localization_node.cpp#L235) line and when using the tf2::TimePointZero or a timeout, I was able to supress these warnings and obtained a more robust localization.

Could you tell me at what rate your scanner is publishing data right now? Also check for the publishing rates of tf and odom. This could also play a big role in the issue we are having right now. If there are some constant delays or fluctuation in the publishing rate, this would be infact causing the issue. 

> i have a similar issue with very frequent output of the following warnings in a simulation setup:

This issue as been popping up for quite some while, since the migration of the package to ROS-2. I can confirm it happens only in the simulation and not with any real sensors as @automech-rb confirmed it in one of the previous comments. I'll take a deeper look this week and will get back to you. I somehow doubt it is related with the higher publishing frequency of the simulated laser scanners or the slower publishing frequency of the odom / tf.

If you are looking for some example parameters, here is a nice example that is set for mpo-700: https://github.com/neobotix/neo_mpo_700-2/blob/rolling/configs/navigation/navigation.yaml

**Comment by padhupradheep** [comment] 2022-09-14 18:19
Alright, I tested once again with our neo_simulation package in Galactic and can confirm that the warning occurs very rarely (once in every ~20 seconds) especially when there is a fluctuations in the publishing rate of the odometery and tf. 

@fmros Could you please check it with your setup and let me know? I can close the issue then.

**Comment by fmros** [comment] 2022-09-26 17:15
> > I traced it down to [this](https://github.com/neobotix/neo_localization2/blob/63728e413e063a46323fb6414b976ca3b51c9e2e/src/neo_localization_node.cpp#L235) line and when using the tf2::TimePointZero or a timeout, I was able to supress these warnings and obtained a more robust localization.
> 
> Could you tell me at what rate your scanner is publishing data right now? Also check for the publishing rates of tf and odom. This could also play a big role in the issue we are having right now. If there are some constant delays or fluctuation in the publishing rate, this would be infact causing the issue.

The scanner is publishing at ~10 Hz at the moment. I also increased it to 20Hz, but no noticeable changes.
I don't see large fluctuations either in /odom nor in /tf by using `ros2 topic hz /topic_name`. Do you measure them differently?

**Comment by padhupradheep** [comment] 2022-09-27 04:10
No no it's the same way I measure them. Could you may be tell me which distro you are using and what rate the odom is being published ?

**Comment by fmros** [comment] 2022-09-27 06:00
> No no it's the same way I measure them. Could you may be tell me which distro you are using and what rate the odom is being published ?

Galactic and /odom is at ~18.4 Hz.

**Comment by automech-rb** [comment] 2022-09-27 06:06
Hi @fmros 
Can you share the tf map generated from following command:
```
ros2 run tf2_tools view_frames --ros-args -p use_sim_time:=true
```

**Comment by fmros** [comment] 2022-09-27 06:08
This tool does not work for me:
```
python3: /tmp/binarydeb/ros-galactic-cyclonedds-0.8.0/src/core/ddsi/src/ddsi_ipaddr.c:305: ddsi_ipaddr_from_loc: Assertion `0' failed.
```

**Comment by padhupradheep** [comment] 2022-09-27 06:17
Okay, I'm pretty sure, this issue is somehow a race condition between your odom data and scanner data. This could also solely depend on the hardware you are using. 

Could you also tell me the real time factor that you can see in simulation ?

**Comment by fmros** [comment] 2022-09-27 06:19
I am running everything completely in simulation. Realtime factor of Gazebo is arround 0.93.

**Comment by padhupradheep** [comment] 2022-09-27 06:40
Could you please share me the link of your simulation setup?

**Comment by fmros** [comment] 2022-09-27 06:42
It is not opensource unfortunately.

**Comment by padhupradheep** [comment] 2022-09-27 06:56
I'm really sorry, I have to close the issue, because I will not be able to reproduce the issue for helping you further. As said before, please try to check the fluctuations for the odom and tf publish rate. If you think, the publishing rate is fluctuating a lot, then I would suggest you to use the solution that you suggested instead of using the scan_time. This is mainly because, your odom data is somehow behind your scanner data in terms of time at which it is published. 

If you have time, you can also do checkout [neo_simulation2](https://github.com/neobotix/neo_simulation2) and see how the localization works over there. 

Please feel free to post if you have any other questions. I'll also be happy to accept a PR, if you think there is some issue within the internal working of the algorithm.

**Closed by padhupradheep** 2022-09-27 06:56 UTC
Labels: bug
